executable              = /afs/cern.ch/work/c/covarell/vbs2017/CMSSW_8_0_26_patch1new/src/vbs_analysis/4l_channel/runAll.sh
output                  = /afs/cern.ch/work/c/covarell/vbs2017/CMSSW_8_0_26_patch1new/src/vbs_analysis/4l_channel/output/$(ClusterId).$(ProcId).out
error                   = /afs/cern.ch/work/c/covarell/vbs2017/CMSSW_8_0_26_patch1new/src/vbs_analysis/4l_channel/error/$(ClusterId).$(ProcId).err
log                     = /afs/cern.ch/work/c/covarell/vbs2017/CMSSW_8_0_26_patch1new/src/vbs_analysis/4l_channel/log/$(ClusterId).log
Initialdir              = /afs/cern.ch/work/c/covarell/vbs2017/CMSSW_8_0_26_patch1new/src/vbs_analysis/4l_channel
+JobFlavour             = "tomorrow"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

Queue 1
